alter table CSGOMARKET_USER_EMPLOYEE add constraint FK_CSGOMARKET_USER_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_CSGOMARKET_USER_EMPLOYEE_ON_USER on CSGOMARKET_USER_EMPLOYEE (USER_ID);
